### PR TITLE
Activate only connections if present in the current system

### LINKED ISSUE #53: Migration fails with `--activate-connections`, if config exists of not existing NIC
### Situation:

* system with **only  one** (physical/virtual) NIC (e.g. `eth0`)
* `ifcfg-eth0` exists, but also a valid config `ifcfg-eth5`
* the systemd service `wicked.service` do not report any error on bootup
  *  because the service is using `wicked --systemd ifup all`, which return `0`
* !! a manual `wicked ifup all` exit with `2` and show `eth5            no-device`

=> Migrating such a system, result in an error like:
```
[ERROR] Migration failed: Could not update the network configuration: D-Bus service error: org.freedesktop.NetworkManager.UnknownDevice: No suitable device found for this connection (device eth0 not available because profile is not compatible with device (mismatching interface name)).
, stdout: (no output on stdout)
```

### PR DESCRIPTION
**Pull request by jcronenberg**
With activate_connections set to true wicked2nm would try to set connections to the 'up' status even if the interface isn't present in the system resulting in some cryptic errors by NetworkManager. Now it checks what interfaces are present and only sets connection with a matching interface present to 'up'.

Fixes #53

### CODE REVIEW

File: src/interface.rs [hunk 1]
```diff
@@ -418,7 +420,8 @@ impl Interface {
         }
 
         if settings.activate_connections {
-            connection.status = if connection.autoconnect {
+            connection.status = if connection.autoconnect && system_interfaces.contains(&self.name)
```
Comment (cfconrad) [inline src/interface.rs:423]: I wonder if it would make sense to put a code block like:
```rust
    if settings.activate_connections {
        let system_interfaces = list_system_interfaces()?;
        for con in &mut connection_result.connections {
            if  con.autoconnect && system_interfaces.contains(&con.id) {
                con.status = Status::Up;
            }
        }
    }
```
to the end of `migrate::to_networkstate()`. Instead of changing the behavior of `to_connection()`

Comment (cfconrad) [reply src/interface.rs:423]: Also, I wonder if it will work with "virtual" interfaces like `Dummy` or `bond`, when these interfaces are **not** created currently.

Comment (jcronenberg) [reply src/interface.rs:423]: I think you mean this but sure I think I like that better as well
```rust
    if settings.activate_connections {
        let system_interfaces = list_system_interfaces()?;
        for con in &mut connection_result.connections {
            if con.autoconnect && !system_interfaces.contains(&con.id) {
                con.status = agama_network::types::Status::Down;
            }
        }
    }
```

Comment (cfconrad) [reply src/interface.rs:423]: ok, regarding my code snippet... it will not work. As the `con.id` might not be the interface name in case of wireless...

Comment (jcronenberg) [reply src/interface.rs:423]: > Also, I wonder if it will work with "virtual" interfaces like `Dummy` or `bond`, when these interfaces are **not** created currently.

Mhm very valid. I guess for dummy it should just be "blacklisted". For bonds I guess it should be "up" if the parent interface exists in the system? Which would also be in favor of the "post-process" approach in `migrate::to_networkstate()`

**Review by cfconrad — APPROVED** [review]
LGTM, thx!
